### ISSUE TITLE
Support for wildcards in handler addresses

### ISSUE THREAD

**Issue by kisielk** [hypebeast/go-osc#10]
The features section in the documentation includes:

    - Support for OSC address pattern including '*', '?', '{,}' and '[]' wildcards

However it looks like it's not actually supported, AddMsgHandler returns an error if it encounters any of those characters.

**Comment by briansorahan** [comment]
This behavior is not part of the OSC spec, but has been discussed on the [liblo issue tracker](http://sourceforge.net/p/liblo/bugs/23/). It seems like a method handler that uses an Address Pattern rather than an Address would want to extract parameters out of the address, but if this is the case then you should remove the 'wildcard' parts of the path you want to match and pass those parameters as arguments.

**Comment by kisielk** [comment]
Yeah that makes sense. I realized I didn't end up needing this feature anyway.
